# Generated by Django 5.0.3 on 2024-04-10 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FULL_NAME', models.CharField(max_length=40)),
                ('EMAIL', models.EmailField(max_length=254, unique=True)),
                ('USERNAME', models.CharField(max_length=20, unique=True)),
                ('PASSWORD', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=40)),
                ('INGREDIENTS', models.TextField()),
                ('INSTRUCTIONS', models.TextField()),
                ('PICTURE', models.FileField(upload_to='')),
                ('AUTHOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='R_app.author')),
            ],
        ),
    ]
